server:
  port: 8085

spring:
  application:
    name : payment-service
  config:
    import: configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/smartparking
    username: root
    password: Ijse@123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

eureka:
  client:
    service_url:
      defaultZone: http://localhost:8761/eureka/