server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: parking-space-service
          uri: lb://parking-space-service
          predicates:
            - Path=/api/parking/**

        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/vehicle/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: Payment-service
          uri: lb://Payment-service
          predicates:
            - Path=/api/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/